/* auth.h - HTTP Basic/Digest + RTSP Digest authentication (no OpenSSL) */
#ifndef MS_AUTH_H
#define MS_AUTH_H

#define AUTH_REALM "timps"

/* HTTP Basic: 'value' is the text after "Authorization: ". Returns 1 if valid. */
int  auth_http_basic(const char *value, const char *user, const char *pass);

/* RTSP Digest: validate an "Authorization: Digest ..." value against
 * method+creds AND the nonce this server actually issued to this session
 * (server_nonce, from auth_make_nonce()) - without that check, a sniffed
 * Authorization header can be replayed indefinitely against any
 * connection using any nonce the client cares to supply, since the digest
 * response is fully reproducible from (user, realm, pass, method, uri,
 * nonce). req_uri is the request-target from the request line: the client's
 * digest "uri" parameter MUST equal it (RFC 2617/7616), else HA2 was computed
 * over an attacker-chosen URI and a response captured for one URI could be
 * replayed against another; pass NULL only to skip that check. Returns 1 if
 * valid. */
int  auth_rtsp_digest(const char *method, const char *req_uri, const char *value,
                      const char *user, const char *pass,
                      const char *server_nonce);

/* HTTP Digest (RFC 7616 qop="auth" and legacy RFC 2069 no-qop responses):
 * validate an "Authorization: Digest ..." value against method+creds. On
 * success the client-supplied nonce (and nc, empty for no-qop) are copied
 * out - the CALLER must additionally verify that nonce is one it recently
 * issued and that nc is fresh (httpd's nonce table), otherwise a sniffed
 * Authorization header would verify forever. req_uri is the request-target
 * from the HTTP request line: the client's digest "uri" parameter MUST equal
 * it (RFC 2617/7616), else HA2 was computed over an attacker-chosen URI and a
 * response captured for one URI could be replayed against another within the
 * nonce window; pass NULL only to skip that check. Returns 1 if the digest is
 * cryptographically valid for user/pass. */
int  auth_http_digest(const char *method, const char *req_uri, const char *value,
                      const char *user, const char *pass,
                      char *nonce_out, int nonce_cap,
                      char *nc_out, int nc_cap);

/* generate a fresh opaque nonce (32 hex chars + NUL) */
void auth_make_nonce(char out[33]);

/* --- /control token auth --- */
/* per-boot random token (32 hex chars; generated by main() at startup and
 * published to local privileged readers via http.token_file) */
extern char g_ctl_token[33];
/* fill out with a fresh 128-bit token, hex-encoded (/dev/urandom; hashed
 * time/pid mix only as a last resort) */
void auth_gen_token(char out[33]);
/* constant-time string equality for secret comparison (no early exit on a
 * content mismatch; the length itself is not secret). Returns 1 if equal. */
int  auth_token_eq(const char *a, const char *b);

#endif
