/* auth.h - HTTP Basic + RTSP Digest authentication (no OpenSSL) */
#ifndef MS_AUTH_H
#define MS_AUTH_H

#define AUTH_REALM "timps"

/* HTTP Basic: 'value' is the text after "Authorization: ". Returns 1 if valid. */
int  auth_http_basic(const char *value, const char *user, const char *pass);

/* RTSP Digest: validate an "Authorization: Digest ..." value against
 * method+creds AND the nonce this server actually issued to this session
 * (server_nonce, from auth_make_nonce()) - without that check, a sniffed
 * Authorization header can be replayed indefinitely against any
 * connection using any nonce the client cares to supply, since the digest
 * response is fully reproducible from (user, realm, pass, method, uri,
 * nonce). Returns 1 if valid. */
int  auth_rtsp_digest(const char *method, const char *value,
                      const char *user, const char *pass,
                      const char *server_nonce);

/* generate a fresh opaque nonce (32 hex chars + NUL) */
void auth_make_nonce(char out[33]);

/* --- /control token auth --- */
/* per-boot random token (32 hex chars; generated by main() at startup and
 * published to local privileged readers via http.token_file) */
extern char g_ctl_token[33];
/* fill out with a fresh 128-bit token, hex-encoded (/dev/urandom; hashed
 * time/pid mix only as a last resort) */
void auth_gen_token(char out[33]);
/* constant-time string equality for secret comparison (no early exit on a
 * content mismatch; the length itself is not secret). Returns 1 if equal. */
int  auth_token_eq(const char *a, const char *b);

#endif
